### PR TITLE
feat: include measured score in failure message

### LINKED ISSUE #14: Output score in test results
As a developer, I want to know what score the lighthouse report assigned

### PR DESCRIPTION
**Pull request by G-Rath**
Fixes #14

### CODE REVIEW

**Comment by G-Rath** [comment]
(it'd be good to have #23 actioned before merging this, just so that releasing it taken care of automatically)

**Review by joshmcarthur — APPROVED** [review]
LGTM, though it has reinforced my belief that we need to do some work around the responsibilities the audit service has so that it's eaiser to access these score results without rerunning the audit.

**Comment by robotdana** [comment]
i think i'll merge #32 in favour of this unless you have a strong attachment to it, it only runs the audit once

**Comment by G-Rath** [comment]
I'm not super fussed, other than to point out we could have landed this one as-is then tackled the "run audit once" in another PR since that'll require more review and #32 is currently failing CI.

**Pull request merged**
